// Nearest-facility lookup for the danger-gate escalation.
//
// Everything here runs on the device. The woman's coordinates are never sent
// to our API, to an LLM, or anywhere else -- a location attached to "I am
// bleeding in pregnancy" is sensitive in a way that outweighs the convenience
// of doing this server-side. The dataset is fetched once, on first escalation,
// and cached in memory for the session.
//
// Source of truth: data/facilities/sindh_health_facilities.json, generated by
// scripts/fetch_health_facilities.py from OpenStreetMap. Never hand-edited and
// never model-generated -- naming a facility that does not exist would send
// someone the wrong way during an emergency.

export type Facility = {
  id: string;
  name: string;
  kind: "dhq" | "thq" | "rhc" | "bhu" | "mch" | "hospital" | "clinic";
  lat: number;
  lon: number;
  district: string;
  phone: string;
  emergency: boolean;
};

export type NearbyFacility = Facility & { km: number };

// Sindhi labels for the tier. The tier is the useful part: a BHU is outpatient
// and may not be able to admit her, a DHQ or THQ hospital usually can.
export const KIND_LABEL: Record<Facility["kind"], string> = {
  dhq: "ضلعي هيڊڪوارٽر اسپتال",
  thq: "تعلقي هيڊڪوارٽر اسپتال",
  rhc: "ڳوٺاڻو صحت مرڪز",
  bhu: "بنيادي صحت يونٽ",
  mch: "ماءُ ۽ ٻار جي صحت جو مرڪز",
  hospital: "اسپتال",
  clinic: "ڪلينڪ",
};

// Facilities that can usually handle an obstetric emergency, best first.
const ADMITS_FIRST: Facility["kind"][] = ["dhq", "thq", "hospital", "mch", "rhc"];

let cache: Facility[] | null = null;

export async function loadFacilities(): Promise<Facility[]> {
  if (cache) return cache;
  const res = await fetch("/sindh_health_facilities.json");
  if (!res.ok) throw new Error(`facility data unavailable: HTTP ${res.status}`);
  const payload = await res.json();
  cache = payload.facilities as Facility[];
  return cache;
}

/** Great-circle distance in km. */
function haversine(aLat: number, aLon: number, bLat: number, bLon: number): number {
  const R = 6371;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(bLat - aLat);
  const dLon = toRad(bLon - aLon);
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(aLat)) * Math.cos(toRad(bLat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

/**
 * Nearest facilities to a point.
 *
 * Ranked by distance, but a place that can admit her is preferred over a
 * marginally closer one that cannot: within `preferWithinKm` of the closest
 * result, an admitting facility sorts first. Sending a haemorrhaging woman
 * 300m to an outpatient BHU instead of 2km to a THQ hospital is the wrong
 * answer even though it is the nearer one.
 */
export function nearest(
  facilities: Facility[],
  lat: number,
  lon: number,
  limit = 3,
  preferWithinKm = 8
): NearbyFacility[] {
  const scored = facilities
    .map((f) => ({ ...f, km: haversine(lat, lon, f.lat, f.lon) }))
    .sort((a, b) => a.km - b.km);

  if (scored.length === 0) return [];

  const floor = scored[0].km;
  const admits = (f: NearbyFacility) => ADMITS_FIRST.includes(f.kind);
  const inBand = scored.filter((f) => f.km <= floor + preferWithinKm);
  const rest = scored.filter((f) => f.km > floor + preferWithinKm);
  inBand.sort((a, b) => {
    const byKind = Number(admits(b)) - Number(admits(a));
    return byKind !== 0 ? byKind : a.km - b.km;
  });

  return [...inBand, ...rest].slice(0, limit);
}

/** Browser geolocation as a promise. Rejects rather than hanging. */
export function getPosition(timeoutMs = 10000): Promise<GeolocationPosition> {
  return new Promise((resolve, reject) => {
    if (typeof navigator === "undefined" || !navigator.geolocation) {
      reject(new Error("geolocation unsupported"));
      return;
    }
    navigator.geolocation.getCurrentPosition(resolve, reject, {
      enableHighAccuracy: false, // a coarse fix is plenty and much faster
      timeout: timeoutMs,
      maximumAge: 300000,
    });
  });
}

/** Distance phrased for a reader, not a developer. */
export function formatKm(km: number): string {
  if (km < 1) return `${Math.round(km * 1000)} ميٽر`;
  return `${km.toFixed(km < 10 ? 1 : 0)} ڪلوميٽر`;
}

/** Directions link. Opens whatever map app the phone already has. */
export function mapsUrl(f: Facility): string {
  return `https://www.google.com/maps/search/?api=1&query=${f.lat},${f.lon}`;
}
